[WIP] Upgrade rancher/fluentd image version to v0.1.19
rancher/system-charts pull request #141
Opened 2019-12-25 07:39 UTC by shanewxy

**Problem**
Fluentd cluster-level logging sends more and more backslashes which end up impossible to read the logs. The root cause is parsing logs to JSON even if it is not in JSON format.
https://github.com/rancher/rancher/issues/24545

**Solution**
Release a new rancher/fluentd image with multi_format plugin installed

2019-12-26 06:01 UTC, loganhz approved these changes

2019-12-26 06:47 UTC, aiwantaozi submitted a review, later dismissed

2019-12-26 07:01 UTC, loganhz requested changes
Please add rancher min version to 2.3.4-rc1

2019-12-26 07:30 UTC, loganhz submitted a review, later dismissed

2019-12-26 18:24 UTC, luthermonson commented
@shanewxy squash the typo commit and this LGTM

2019-12-27 01:45 UTC, shanewxy commented
rebased

2019-12-27 03:27 UTC, deniseschannon approved these changes

2019-12-27 03:27 UTC, merged