[2.3] Add Istio 1.4.800
rancher/system-charts pull request #216
Opened 2020-05-05 17:17 UTC by brendarearden

rancher/rancher#26784

2020-05-07 16:13 UTC, cbron submitted a review, later dismissed

2020-05-07 17:35 UTC, cbron submitted a review, later dismissed
lgtm, 2.3.7rc1 is end of 1.4.7 and start of 1.4.8

2020-05-08 23:01 UTC, deniseschannon requested changes

2020-05-08 23:01 UTC, deniseschannon commented on charts/rancher-istio/1.4.700/questions.yaml
> +rancher_max_version: 2.3.7-rc1
Update to `2.3.6`.

2020-05-09 01:11 UTC, deniseschannon approved these changes

2020-05-09 01:11 UTC, merged