[WIP] [Ready For Review] Add chart webhook-receiver
rancher/system-charts pull request #263
Opened 2020-06-22 07:47 UTC by GGGitBoy

Add the chart webhook-receiver to support DingTalk and Microsoft Teams as the notifier

Related Issue:

https://github.com/rancher/rancher/issues/15802
https://github.com/rancher/rancher/issues/19537

Related PR:

https://github.com/rancher/rancher/pull/25251

2020-06-24 09:12 UTC, guangbochen commented on charts/rancher-monitoring/v0.1.2/charts/webhook-receiver/Chart.yaml
> +  email: logan@rancher.com
can u please fix those newline issues.

2020-06-24 09:15 UTC, guangbochen reviewed
@GGGitBoy can u fix those format issues, everything else is LGTM, thanks.

2020-06-24 09:15 UTC, guangbochen commented on charts/rancher-monitoring/v0.1.2/charts/webhook-receiver/templates/deployment.yaml
> +          secretName: webhook-receiver
same as above

2020-06-24 09:15 UTC, guangbochen commented on charts/rancher-monitoring/v0.1.2/charts/webhook-receiver/templates/secret.yaml
> +  config.yaml: {{ toYaml ( required "you must provide config for init" .Values.config ) | b64enc }}
same as above

2020-06-24 09:15 UTC, guangbochen commented on charts/rancher-monitoring/v0.1.2/charts/webhook-receiver/templates/service.yaml
> +      targetPort: {{ .Values.port }}
same as above

2020-06-24 09:15 UTC, guangbochen commented on charts/rancher-monitoring/v0.1.2/charts/webhook-receiver/values.yaml
> +port: 9094
same as above

2020-06-24 11:15 UTC, GGGitBoy commented
@guangbochen Update!

2020-06-24 13:39 UTC, guangbochen submitted a review, later dismissed
LGTM, thanks

2020-07-16 04:03 UTC, aiyengar2 commented on charts/rancher-monitoring/v0.1.2/charts/webhook-receiver/templates/deployment.yaml
> +{{ toYaml .Values.resources | indent 12 }}
```suggestion
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
{{- end }}
```

2020-07-16 04:03 UTC, aiyengar2 commented on charts/rancher-monitoring/v0.1.2/charts/webhook-receiver/templates/deployment.yaml
> +    release: {{ .Release.Name }}
nit:
@GGGitBoy can we potentially put these into a `_helpers.tpl` to avoid repeating the labels several times? i.e. contents could be:
```yaml
{{- define "webhook-receiver.labels" -}}
app: {{ template "app.name" . }}
chart: {{ template "app.version" . }}
heritage: {{ .Release.Service }}
release: {{ .Release.Name }}
{{- end -}}
```

where references within all of the YAMLs are changed to:

```yaml
{{ include "webhook-receiver.labels" . | indent <amount-of-indent-required> }}
```

2020-07-16 04:03 UTC, aiyengar2 commented on charts/rancher-monitoring/v0.1.2/charts/webhook-receiver/templates/deployment.yaml
> +    release: {{ .Release.Name }}
nit: 
Is there a particular reason why the `heritage` label is here but not within the Deployment spec selector, Pod spec, or Service spec selector?

2020-07-16 07:39 UTC, GGGitBoy commented
@aiyengar2 Update, thanks

2020-07-16 17:51 UTC, aiyengar2 requested changes

2020-07-16 17:51 UTC, aiyengar2 commented on charts/rancher-monitoring/v0.1.3/charts/webhook-receiver/templates/deployment.yaml
> +      release: {{ .Release.Name }}
```suggestion
  selector:
    matchLabels: {{- include "webhook-receiver.labels" . | nindent 6 }}
```

2020-07-16 17:51 UTC, aiyengar2 commented on charts/rancher-monitoring/v0.1.3/charts/webhook-receiver/templates/deployment.yaml
> +        release: {{ .Release.Name }}
```suggestion
    metadata:
      labels: {{- include "webhook-receiver.labels" . | nindent 8 }}
```

2020-07-16 17:51 UTC, aiyengar2 commented on charts/rancher-monitoring/v0.1.3/charts/webhook-receiver/templates/service.yaml
> +    release: {{ .Release.Name }}
```suggestion
  selector: {{- include "webhook-receiver.labels" . | nindent 4 }}
```

2020-07-16 17:51 UTC, aiyengar2 commented on charts/rancher-monitoring/v0.1.3/charts/webhook-receiver/templates/service.yaml
> +{{- include "webhook-receiver.labels" . | nindent 4 }}
```suggestion
{{- include "webhook-receiver.labels" . | indent 4 }}
```

2020-07-16 17:51 UTC, aiyengar2 commented on charts/rancher-monitoring/v0.1.3/charts/webhook-receiver/templates/deployment.yaml
> +{{- include "webhook-receiver.labels" . | nindent 4 }}
nindent should create a new line.

```suggestion
  labels: {{- include "webhook-receiver.labels" . | nindent 4 }}
```

2020-07-16 17:51 UTC, aiyengar2 commented on charts/rancher-monitoring/v0.1.3/charts/webhook-receiver/templates/deployment.yaml
> +{{ toYaml .Values.affinity | indent 10 }}
```suggestion
        affinity: {{ toYaml .Values.affinity | nindent 10 }}
```

2020-07-16 17:51 UTC, aiyengar2 commented on charts/rancher-monitoring/v0.1.3/charts/webhook-receiver/templates/deployment.yaml
> +{{ toYaml .Values.nodeSelector | indent 10 }}
```suggestion
        nodeSelector: {{ toYaml .Values.nodeSelector | nindent 10 }}
```

2020-07-16 17:51 UTC, aiyengar2 commented on charts/rancher-monitoring/v0.1.3/charts/webhook-receiver/templates/deployment.yaml
> +{{ toYaml .Values.tolerations | indent 10 }}
```suggestion
        tolerations: {{ toYaml .Values.tolerations | nindent 10 }}
```

2020-07-16 17:51 UTC, aiyengar2 commented on charts/rancher-monitoring/v0.1.3/charts/webhook-receiver/templates/deployment.yaml
> +{{ toYaml .Values.resources | indent 12 }}
```suggestion
        resources: {{ toYaml .Values.resources | nindent 12 }}
```

2020-07-16 17:51 UTC, aiyengar2 commented on charts/rancher-monitoring/v0.1.3/charts/webhook-receiver/templates/secret.yaml
> +{{- include "webhook-receiver.labels" . | nindent 4 }}
```suggestion
  labels: {{- include "webhook-receiver.labels" . | nindent 4 }}
```

2020-07-16 23:40 UTC, aiyengar2 submitted a review, later dismissed
Thank you for making the changes! LGTM 👍

2020-07-17 17:11 UTC, prachidamle commented on charts/rancher-monitoring/v0.1.3/Chart.yaml
> +description: Provides monitoring for Kubernetes which maintaining by Rancher 2.
nit: which is maintaining by Rancher 2

2020-07-20 06:31 UTC, GGGitBoy commented
@prachidamle Fix, thanks!

2020-07-22 01:48 UTC, GGGitBoy commented
rebase

2020-07-22 16:05 UTC, dramich requested changes

2020-07-22 16:05 UTC, dramich commented on charts/rancher-monitoring/v0.1.3/Chart.yaml
> +description: Provides monitoring for Kubernetes which is maintaining by Rancher 2.
```suggestion
description: Provides monitoring for Kubernetes which is maintained by Rancher 2.
```

2020-07-22 16:05 UTC, dramich commented on charts/rancher-monitoring/v0.1.3/README.md
> +    * Added chart webhook-receiver to support some recipients those not directly supported by Prometheus. Such as DingTalk and Microsoft Teams, etc.
```suggestion
    * Added chart webhook-receiver to support recipients that are not directly supported by Prometheus
```

2020-07-22 16:05 UTC, dramich commented on charts/rancher-monitoring/v0.1.3/charts/webhook-receiver/Chart.yaml
> +description: The webhook receiver of Prometheus
```suggestion
description: Rancher webhook receiver for Prometheus
```

2020-07-23 01:38 UTC, GGGitBoy commented
@dramich Fix, thanks!

2020-07-23 16:19 UTC, dramich submitted a review, later dismissed

2020-07-24 03:01 UTC, GGGitBoy commented
Wait for https://github.com/rancher/image-mirror/pull/14

2020-07-24 03:06 UTC, GGGitBoy commented
Rebase and wait for https://github.com/rancher/image-mirror/pull/14

2020-07-25 22:09 UTC, GGGitBoy commented
Rebase and update webhook-reveiver image to `rancher/webhook-receiver:v0.2.4`

2020-07-27 16:49 UTC, dramich approved these changes

2020-07-27 16:49 UTC, merged