Sync gke-operator 1.0.200 package from 2.5.9
rancher/system-charts pull request #508
Opened 2021-07-14 16:55 UTC by cmurphy

2021-07-14 16:57 UTC, cbron approved these changes

2021-07-14 16:58 UTC, cbron requested changes
This should be 1.0.300

2021-07-14 17:16 UTC, thedadams submitted a review, later dismissed

2021-07-14 17:24 UTC, cbron commented on charts/rancher-gke-operator/1.0.300/values.yaml
>  httpsProxy: ""
I think 1.0.300 should have more changes no ? Looks like questions.yaml is still set on old one: https://github.com/rancher/system-charts/blob/be12cf837e206bd3b8917b5cb3ea626f103427e0/charts/rancher-gke-operator/1.0.300/questions.yaml

2021-07-14 19:36 UTC, cbron approved these changes

2021-07-15 00:05 UTC, thedadams approved these changes

2021-07-15 17:09 UTC, merged