release-v2.6
rancher/system-charts pull request #517
Opened 2021-08-10 16:46 UTC by kinarashah

2021-08-24 14:44 UTC, kinarashah commented
@aiyengar2 Fixed the issue of conflicting files. New commits from dev-v2.6 will be pulled automatically, but PR is ready for review now.

2021-08-25 17:42 UTC, aiyengar2 commented
Since the diff on GitHub is hard to review, I pulled in the charts/ directory from release-v2.5 into `2.5-charts/` and the charts/ directory from dev-v2.6 into `2.6-charts/` and manually reviewed the diffs on everything. I produced the diffs based on the following script:

```bash
OLD_CHART_DIR=2.5-charts
NEW_CHART_DIR=2.6-charts

rm -rf diffs_in_prior_chart_versions
mkdir -p diffs_in_prior_chart_versions

rm -rf diffs_in_latest_version
mkdir -p diffs_in_latest_version

for chart in $(ls ${OLD_CHART_DIR}); do

    latest_chart_version=$(ls ${NEW_CHART_DIR}/${chart} | sort -r | head -n 1)
    prior_chart_version=$(ls ${OLD_CHART_DIR}/${chart} | sort -r | head -n 1)

    diff -uNr ${OLD_CHART_DIR}/${chart} ${NEW_CHART_DIR}/${chart} > diffs_in_prior_chart_versions/${chart}.diff;

    diff -uNr  ${OLD_CHART_DIR}/${chart}/${prior_chart_version} ${NEW_CHART_DIR}/${chart}/${latest_chart_version} > diffs_in_latest_version/${chart}.diff

done
```

This simulates the difference in charts directories that would be observed if a user were to migrate from v2.5.9 -> v2.6.0, which needs to be consistent.

---

Here is the checklist template I am using to verify that the chart looks good for any modified charts (@cbron we should consider adding this to the release checklist):
- [ ] Was a new chart version introduced?
  - Previous Chart Version: `PLACEHOLDER`
  - Latest Chart Version: `PLACEHOLDER`
- [ ] [Minor Release ONLY] Is the latest chart version's minor version +1 the previous chart's major version? e.g. 1.0.0 -> 1.1.0
  - If not, why wasn't it bumped?
```
N/A
```
- [ ] Were the **only** charts that were modified the previous chart version or latest chart version?
  - If not, what else was changed?
```
N/A
```
- [ ] Did we add a `rancher_max_version` annotation to the previous version's `questions.yaml`?
  - rancher_max_version: `PLACEHOLDER`
- [ ] Was the previous version otherwise unchanged?
- [ ] Did we add a `rancher_min_version` annotation to the latest version's `questions.yaml`?
  - rancher_min_version: `PLACEHOLDER`
- [ ] Did you confirm that there are no RC versions introduced in the image tags that were modified?
- [ ] Did you ensure the Chart.yaml was modified to match the new version of the folder?
- [ ] Did you confirm that there were no other breaking changes introduced? If so, tag the SME to confirm that it looks good.


### Removed Charts
- rancher-eks-operator
- rancher-gke-operator

Even though removed charts are normally a cause for concern, this is reasonable since, on an upgrade, Rancher will forcibly update these two charts if they exist to the latest that is contained within feature-charts. 

**LGTM**

---

### New Charts

No new charts have been added to system-charts. 

**LGTM**

---

### Modified Charts

#### rancher-cis-benchmark
- [x] Was a new chart version introduced?
  - Previous Chart Version: `0.1.2`
  - Latest Chart Version: `0.2.0`
- [x] [Minor Release ONLY] Is the latest chart version's minor version +1 the previous chart's major version? e.g. 1.0.0 -> 1.1.0
  - If not, why wasn't it bumped?
```
N/A
```
- [x] Were the **only** charts that were modified the previous chart version or latest chart version?
  - If not, what else was changed?
```
N/A
```
- [x] Did we add a `rancher_max_version` annotation to the previous version's `questions.yaml`?
  - rancher_max_version: `2.5.8`
- [x] Was the previous version otherwise unchanged?
- [x] Did we add a `rancher_min_version` annotation to the latest version's `questions.yaml`?
  - rancher_min_version: `2.6.0-alpha1`
- [x] Did you confirm that there are no RC versions introduced in the image tags that were modified?
- [x] Did you ensure the Chart.yaml was modified to match the new version of the folder?
- [x] Did you confirm that there were no other breaking changes introduced? If so, tag the SME to confirm that it looks good.

**LGTM**

#### rancher-external-dns
- [x] Was a new chart version introduced?
  - Previous Chart Version: `v0.1.2`
  - Latest Chart Version: `v0.2.0`
- [x] [Minor Release ONLY] Is the latest chart version's minor version +1 the previous chart's major version? e.g. 1.0.0 -> 1.1.0
  - If not, why wasn't it bumped?
```
N/A
```
- [x] Were the **only** charts that were modified the previous chart version or latest chart version?
  - If not, what else was changed?
```
We updated the rancher-max-versions across all old, already-released charts to be 2.5.8.
```
- [x] Did we add a `rancher_max_version` annotation to the previous version's `questions.yaml`?
  - rancher_max_version: `2.5.8`
- [x] Was the previous version otherwise unchanged?
- [x] Did we add a `rancher_min_version` annotation to the latest version's `questions.yaml`?
  - rancher_min_version: `2.5.9-alpha1`
- [x] Did you confirm that there are no RC versions introduced in the image tags that were modified?
- [x] Did you ensure the Chart.yaml was modified to match the new version of the folder?
- [x] Did you confirm that there were no other breaking changes introduced? If so, tag the SME to confirm that it looks good.

**NEEDS TO CHANGE: rancher_min_version: `2.5.9-alpha1` is incorrect on rancher-external-dns**

#### rancher-gatekeeper-operator
- [ ] Was a new chart version introduced?
  - Previous Chart Version: `PLACEHOLDER`
  - Latest Chart Version: `PLACEHOLDER`
- [ ] [Minor Release ONLY] Is the latest chart version's minor version +1 the previous chart's major version? e.g. 1.0.0 -> 1.1.0
  - If not, why wasn't it bumped?
```
N/A
```
- [ ] Were the **only** charts that were modified the previous chart version or latest chart version?
  - If not, what else was changed?
```
N/A
```
- [ ] Did we add a `rancher_max_version` annotation to the previous version's `questions.yaml`?
  - rancher_max_version: `PLACEHOLDER`
- [ ] Was the previous version otherwise unchanged?
- [ ] Did we add a `rancher_min_version` annotation to the latest version's `questions.yaml`?
  - rancher_min_version: `PLACEHOLDER`
- [ ] Did you confirm that there are no RC versions introduced in the image tags that were modified?
- [ ] Did you ensure the Chart.yaml was modified to match the new version of the folder?
- [ ] Did you confirm that there were no other breaking changes introduced? If so, tag the SME to confirm that it looks good.

**NEEDS TO CHANGE: No new release line introduced for minor release. @cbron is this okay?**

#### rancher-istio
- [x] Was a new chart version introduced?
  - Previous Chart Version: `1.5.901`
  - Latest Chart Version: `1.5.920`
- [ ] [Minor Release ONLY] Is the latest chart version's minor version +1 the previous chart's major version? e.g. 1.0.0 -> 1.1.0
  - If not, why wasn't it bumped?
```
Unsure. This does not look right.
```
- [x] Were the **only** charts that were modified the previous chart version or latest chart version?
  - If not, what else was changed?
```
N/A
```
- [x] Did we add a `rancher_max_version` annotation to the previous version's `questions.yaml`?
  - rancher_max_version: `2.5.99`
- [x] Was the previous version otherwise unchanged?
- [x] Did we add a `rancher_min_version` annotation to the latest version's `questions.yaml`?
  - rancher_min_version: `2.6.0-rc1`
- [x] Did you confirm that there are no RC versions introduced in the image tags that were modified?
- [x] Did you ensure the Chart.yaml was modified to match the new version of the folder?
- [x] Did you confirm that there were no other breaking changes introduced? If so, tag the SME to confirm that it looks good.

**NEEDS TO CHANGE: Minor version was not bumped. Is this intentional?**

**NEEDS TO CHANGE: rancher-max-version should be consistent. We need to change this to 2.5.8 or standardize all charts to 2.5.99**

#### rancher-k3s-upgrader
- [x] Was a new chart version introduced?
  - Previous Chart Version: `0.3.0`
  - Latest Chart Version: `0.2.1`
- [x] [Minor Release ONLY] Is the latest chart version's minor version +1 the previous chart's major version? e.g. 1.0.0 -> 1.1.0
  - If not, why wasn't it bumped?
```
N/A
 [...]

2021-08-25 18:00 UTC, cbron reviewed
Only actual problem looks to be logging and k3s-upgrader

2021-08-25 18:00 UTC, cbron commented on charts/rancher-external-dns/v0.2.0/questions.yml
> +rancher_min_version: 2.5.9-alpha1
This is odd but I think its ok. In 2.6 it will have the effect of only allowing this. But we can't/won't be backporting 0.2.0 to 2.5.x line. None of the versions in 2.5.x have a questions.yaml

2021-08-25 18:00 UTC, cbron commented on charts/rancher-istio/1.5.920/Chart.yaml
> +version: 1.5.920
This is ok, it was done only to handle mirrored images. It will not be backported to 2.5.x.

2021-08-25 18:00 UTC, cbron commented on charts/rancher-k3s-upgrader/0.3.0/questions.yml
> +rancher_min_version: 2.4.0-rc1
@kinarashah shouldn't 0.2.1 be maxed at 2.5.99, so that users installing fresh on 2.6.0 only have this option.
 https://github.com/rancher/system-charts/blob/release-v2.6/charts/rancher-k3s-upgrader/0.2.1/questions.yml

2021-08-25 18:00 UTC, cbron commented on charts/rancher-logging/0.2.5/Chart.yaml
> +version: 0.2.5
@paynejacob / @nickgerace I don't think we can release this with 2.6.0.

2021-08-25 18:00 UTC, cbron commented on charts/rancher-monitoring/v0.3.0/questions.yml
> +rancher_min_version: 2.5.9-rc1
Doesn't technically matter but 2.6.0-alpha1 would be more correct.

2021-08-25 18:02 UTC, kinarashah commented on charts/rancher-k3s-upgrader/0.3.0/questions.yml
> +rancher_min_version: 2.4.0-rc1
Yeah, looks like the max version wasn't set when 0.3.0 was introduced. I'll put up a PR to update max version.

2021-08-25 19:06 UTC, aiyengar2 requested changes
Summary of changes required from https://github.com/rancher/system-charts/pull/517#issuecomment-905742210:

#### rancher-external-dns

- rancher_min_version: 2.5.9-alpha1 is incorrect. Should be 2.6.0-rc1

#### rancher-gatekeeper-operator

- No new version introduced? @cbron do we just need to fork a new version or is that unnecessary atm?

#### rancher-istio

- Minor version was not bumped. Is this intentional? cc: @brendarearden
- rancher-max-version should be consistent. We need to change this to 2.5.8 instead of 2.5.99.

#### rancher-k3s-upgrader

- rancher_max_version not introduced to previous chart version. Should be 2.5.8
- rancher_min_version not introduced to newest chart version. Should be 2.6.0-rc1

#### rancher-logging

- Multiple Logging charts were introduced. 0.2.5 needs to be deleted.
- rancher_max_version not introduced to previous chart version. Should be 2.5.8
- rancher-min-version should be consistent. Should be 2.6.0-rc1

#### rancher-monitoring

- rancher-min-version should be consistent. Should be 2.6.0-rc1

2021-08-25 19:46 UTC, nickgerace commented on charts/rancher-logging/0.2.5/Chart.yaml
> +version: 0.2.5
Addressed: https://github.com/rancher/system-charts/pull/526

2021-08-25 19:51 UTC, cbron commented
In reference to above comments

* rancher-external-dns: agree
* rancher-gatekeeper-operator: not mandatory to create new version, we'll bump when necessary
* rancher-istio: we can't bump the minor version, its linked to upstream, thats why patch version bumped so much. On version change, I'd prefer 2.5.99 since one doesn't exist in the 2.5 branch for this chart. 
* rancher-k3s-upgrader: agree
* rancher-logging: agree on first point, but would prefer 2.5.99, and min version can be rc0 ? Technically they should all be alpha1. 
* rancher-monitoring: agree

2021-08-26 15:53 UTC, aiyengar2 commented
> In reference to above comments
> 
> * rancher-external-dns: agree
> * rancher-gatekeeper-operator: not mandatory to create new version, we'll bump when necessary
> * rancher-istio: we can't bump the minor version, its linked to upstream, thats why patch version bumped so much. On version change, I'd prefer 2.5.99 since one doesn't exist in the 2.5 branch for this chart.
> * rancher-k3s-upgrader: agree
> * rancher-logging: agree on first point, but would prefer 2.5.99, and min version can be rc0 ? Technically they should all be alpha1.
> * rancher-monitoring: agree

@kinarashah based on this, can you ensure that all previous versions of a chart standardize on `2.5.99` for rancher_max_version? You can take a look at the min versions shown in my comment above to see which charts need that change.

Also, let's standardize rancher_min_versions of the newest charts to `2.6.0-alpha1`.

2021-08-28 00:26 UTC, aiyengar2 commented
All rancher_min_versions and rancher_max_versions have been verified and standardized in https://github.com/rancher/system-charts/pull/527.

As Caleb mentioned, we are not bumping rancher-gatekeeper.

As Caleb mentioned, rancher-istio minor version was not bumped intentionally.

Logging 0.2.5 was deleted as part of https://github.com/rancher/system-charts/pull/526.

@kinarashah, once we merge https://github.com/rancher/system-charts/pull/527, as long as no other changes were made we should be good to merge.

2021-08-28 21:44 UTC, cbron approved these changes

2021-08-30 14:59 UTC, aiyengar2 approved these changes
LGTM

2021-08-30 15:45 UTC, merged