Updating memory and cpu Monitoring v1 limits
rancher/system-charts pull request #538
Opened 2021-09-27 22:45 UTC by prachidamle

2021-09-29 23:12 UTC, jiaqiluo requested changes

2021-09-29 23:12 UTC, jiaqiluo commented on charts/rancher-monitoring/v0.2.3/Chart.yaml
> +version: 0.2.2
```suggestion
version: 0.2.3
```

2021-10-04 17:49 UTC, jiaqiluo approved these changes

2022-01-25 18:01 UTC, MKlimuszka commented
@prachidamle , I came across this PR while reviewing "critical" tickets. Is there a reason this never got merged?

2022-01-25 20:36 UTC, prachidamle commented
@MKlimuszka yeah this was missed in 2.5, will be targeting it for 2.6.4 now

2022-01-25 20:36 UTC, closed without merging