Update k3s-upgrader to v0.9.1
rancher/system-charts pull request #567
Opened 2022-07-11 14:15 UTC by rohitsakala

2022-07-12 10:11 UTC, thehejik requested changes
Also kubectl image `rancher/kubectl:v1.20.2` doesn't exist for `s390x` and the job for upgrade plan in failing then. Latest available (from v1.20.x) for all platforms is `rancher/kubectl:v1.20.15` (verified as working for upgrade of imported k3s)

2022-07-15 06:30 UTC, rohitsakala commented
> Also kubectl image `rancher/kubectl:v1.20.2` doesn't exist for `s390x` and the job for upgrade plan in failing then. Latest available (from v1.20.x) for all platforms is `rancher/kubectl:v1.20.15` (verified as working for upgrade of imported k3s).
> 
> The `kubectl.image.tag`value is defined in `values.yaml` few lines below current changes.

Done.

2022-07-15 08:20 UTC, thehejik approved these changes
LGTM

2022-07-15 16:57 UTC, kinarashah approved these changes

2022-07-15 16:57 UTC, merged