add rancher-k3s-upgrader 0.4.1
rancher/system-charts pull request #589
Opened 2023-05-12 00:06 UTC by jiaqiluo

Issue: https://github.com/rancher/rancher/issues/41511

This PR adds a new version, 0.4.1, for the chart  rancher-k3s-upgrader.
Noticeable change between 0.4.1 and 0.4.0 are:
- bump the tag of the image rancher/system-upgrade-controller to v0.11.0
- fix the value of rancher_min_version.  This did not cause any issues because v0.4.0 is available only in rancher 2.7.x

2023-05-12 16:54 UTC, HarrisonWAffel submitted a review, later dismissed

2023-05-12 17:17 UTC, Oats87 requested changes
Per offline discussion, we should probably bump the "minor" version of the chart if we are going to be removing K8s version support for older versions.

2023-05-15 21:45 UTC, jakefhyde approved these changes

2023-05-15 21:50 UTC, a-blender approved these changes
LGTM

2023-05-15 21:54 UTC, Oats87 approved these changes

2023-05-15 21:55 UTC, merged