[v2.9] Remove PSP references
rancher/system-charts pull request #606
Opened 2024-05-09 09:41 UTC by chiukapoor

### Update
* Update min kubeversion to >= 1.25.0
* Remove PSP references from the chart

### Issue
* https://github.com/rancher/rancher/issues/44922

2024-05-16 21:11 UTC, kinarashah commented
@chiukapoor Could you update `rancher/system-upgrade-controller` to latest `v0.13.4` as part of bumping things for v1.29?

2024-05-17 05:10 UTC, kinarashah approved these changes, later dismissed

2024-05-17 05:12 UTC, kinarashah commented
@jakefhyde / @jiaqiluo could you take a look?

2024-05-17 22:16 UTC, jiaqiluo requested changes

2024-05-17 22:16 UTC, jiaqiluo commented on charts/rancher-k3s-upgrader/0.7.0/Chart.yaml
>  appVersion: v0.13.1
```suggestion
appVersion: v0.13.4
```

2024-05-20 05:03 UTC, chiukapoor commented on charts/rancher-k3s-upgrader/0.7.0/Chart.yaml
>  appVersion: v0.13.1
Updated

2024-05-21 17:14 UTC, kinarashah approved these changes

2024-05-21 17:19 UTC, jiaqiluo approved these changes

2024-05-21 18:13 UTC, merged